using Callable0 = int(int);
using Callable1 = Callable0*(int);
using Callable2 = Callable1*(int);
using Callable3 = Callable2*(int);
using Callable4 = Callable3*(int);
using Callable5 = Callable4*(int);
using Callable6 = Callable5*(int);
using Callable7 = Callable6*(int);
using Callable8 = Callable7*(int);
using Callable9 = Callable8*(int);
using Callable10 = Callable9*(int);
using Callable11 = Callable10*(int);
using Callable12 = Callable11*(int);
using Callable13 = Callable12*(int);
using Callable14 = Callable13*(int);
using Callable15 = Callable14*(int);
using Callable16 = Callable15*(int);
using Callable17 = Callable16*(int);
using Callable18 = Callable17*(int);
using Callable19 = Callable18*(int);
using Callable20 = Callable19*(int);
using Callable21 = Callable20*(int);
using Callable22 = Callable21*(int);
using Callable23 = Callable22*(int);
using Callable24 = Callable23*(int);
using Callable25 = Callable24*(int);
using Callable26 = Callable25*(int);
using Callable27 = Callable26*(int);
using Callable28 = Callable27*(int);
using Callable29 = Callable28*(int);
using Callable30 = Callable29*(int);
using Callable31 = Callable30*(int);
using Callable32 = Callable31*(int);
using Callable33 = Callable32*(int);
using Callable34 = Callable33*(int);
using Callable35 = Callable34*(int);
using Callable36 = Callable35*(int);
using Callable37 = Callable36*(int);
using Callable38 = Callable37*(int);
using Callable39 = Callable38*(int);
using Callable40 = Callable39*(int);
using Callable41 = Callable40*(int);
using Callable42 = Callable41*(int);
using Callable43 = Callable42*(int);
using Callable44 = Callable43*(int);
using Callable45 = Callable44*(int);
using Callable46 = Callable45*(int);
using Callable47 = Callable46*(int);
using Callable48 = Callable47*(int);
using Callable49 = Callable48*(int);
using Callable50 = Callable49*(int);
using Callable51 = Callable50*(int);
using Callable52 = Callable51*(int);
using Callable53 = Callable52*(int);
using Callable54 = Callable53*(int);
using Callable55 = Callable54*(int);
using Callable56 = Callable55*(int);
using Callable57 = Callable56*(int);
using Callable58 = Callable57*(int);
using Callable59 = Callable58*(int);
using Callable60 = Callable59*(int);
using Callable61 = Callable60*(int);
using Callable62 = Callable61*(int);
using Callable63 = Callable62*(int);
using Callable64 = Callable63*(int);
struct DeepStaticCallable {
	static Callable32* (*callbacks)[2];
};
static_assert(__is_same(Callable64, Callable64));
static_assert(!__is_same(Callable64, Callable63));
int main() {
	return __is_same(Callable64, Callable64) &&
			!__is_same(Callable64, Callable63)
		? 42
		: 1;
}
