#!/bin/bash
# FlashCpp C++20 Integration Test Runner
# This script verifies the integration test with standard clang++

set -e  # Exit on error

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TEST_FILE="$SCRIPT_DIR/cpp20_simple_integration_test.cpp"
OUTPUT_EXE="/tmp/flashcpp_integration_test.exe"

echo "======================================================================"
echo "FlashCpp C++20 Integration Test"
echo "======================================================================"
echo ""
echo "Test File: cpp20_simple_integration_test.cpp"
echo "Coverage: 290 test points across 9 C++20 feature categories"
echo ""

echo "Compiling with standard clang++..."
if clang++ -std=c++20 "$TEST_FILE" -o "$OUTPUT_EXE" 2>&1 | grep -E "(error|warning)"; then
    echo ""
    echo "Note: Warnings above are expected (tautological comparisons)"
fi

echo ""
echo "Running integration test..."
if "$OUTPUT_EXE"; then
    EXIT_CODE=$?
    echo ""
    echo "======================================================================"
    echo "✅ TEST RESULT: SUCCESS (Exit code: $EXIT_CODE)"
    echo "======================================================================"
    echo ""
    echo "All 290 test points passed! The integration test successfully covers:"
    echo ""
    echo "  [30 pts] Basic Types & Literals"
    echo "           • Integer types (char, short, int, long, unsigned)"
    echo "           • Floating-point types (float, double)"
    echo "           • Boolean and nullptr"
    echo "           • Hex literals"
    echo ""
    echo "  [50 pts] Operators"
    echo "           • Arithmetic: +, -, *, /, %"
    echo "           • Bitwise: &, |, ^, <<, >>"
    echo "           • Logical: &&, ||, !"
    echo "           • Comparison: ==, !=, <, >, <=, >="
    echo "           • Compound assignment: +=, -=, *=, /="
    echo "           • Increment/decrement: ++, --"
    echo ""
    echo "  [50 pts] Control Flow"
    echo "           • if/else statements"
    echo "           • for, while, do-while loops"
    echo "           • switch/case statements"
    echo "           • break and continue"
    echo ""
    echo "  [20 pts] Functions"
    echo "           • Function declarations and definitions"
    echo "           • Function overloading"
    echo "           • Function pointers"
    echo "           • Trailing return type (auto func() -> type)"
    echo ""
    echo "  [30 pts] Classes and OOP"
    echo "           • Basic class declarations"
    echo "           • Constructors and member functions"
    echo "           • Inheritance and virtual functions"
    echo "           • new/delete operators"
    echo ""
    echo "  [30 pts] Templates"
    echo "           • Function templates with type deduction"
    echo "           • Class templates"
    echo "           • Class Template Argument Deduction (CTAD)"
    echo "           • Variadic templates"
    echo "           • Fold expressions"
    echo ""
    echo "  [10 pts] Constexpr"
    echo "           • Constexpr variables"
    echo "           • Constexpr functions"
    echo "           • Constexpr recursion (factorial)"
    echo "           • static_assert"
    echo ""
    echo "  [10 pts] Lambdas"
    echo "           • Lambda expressions with no captures"
    echo "           • Lambda parameters"
    echo "           • Value and reference captures"
    echo "           • Immediately invoked lambdas"
    echo ""
    echo "  [60 pts] Modern C++ Features"
    echo "           • Auto type deduction"
    echo "           • Decltype"
    echo "           • Typedef and using declarations"
    echo "           • Enumerations and enum classes"
    echo "           • Unions"
    echo "           • Designated initializers"
    echo ""
    echo "This integration test provides comprehensive verification of C++20"
    echo "features (excluding coroutines, modules, and multithreading as requested)."
    echo ""
    exit 0
else
    EXIT_CODE=$?
    echo ""
    echo "======================================================================"
    echo "❌ TEST RESULT: FAILURE (Exit code: $EXIT_CODE)"
    echo "======================================================================"
    echo ""
    echo "Some tests failed. Missing points: $EXIT_CODE"
    echo "See cpp20_simple_integration_test.cpp for details."
    exit $EXIT_CODE
fi

