#pragma once

// Platform-specific runtime function declarations
// This file provides declarations for platform-specific runtime functions
// used by the compiler's code generation.

#ifdef _WIN32
// Windows-specific runtime functions

// Exception handling
// _CxxThrowException is the MSVC C++ runtime function for throwing exceptions
// Signature: void _CxxThrowException(void* pExceptionObject, _ThrowInfo* pThrowInfo)
extern "C" void _CxxThrowException(void* pExceptionObject, void* pThrowInfo);

// Process termination
// ExitProcess is a Windows API function for terminating a process
extern "C" __declspec(dllimport) void __stdcall ExitProcess(unsigned int uExitCode);

// RTTI support
// Windows uses a specific RTTI format with type descriptors
// Format: ??_R0 for type descriptor, ??_R1 for base class descriptor, etc.
// These are generated by the compiler and used by dynamic_cast

#else
// Linux/ELF-specific runtime functions

// Exception handling (not yet implemented for Linux)
// TODO: Implement Linux exception handling using Itanium C++ ABI
// This requires:
// - __cxa_allocate_exception
// - __cxa_throw  
// - __cxa_begin_catch
// - __cxa_end_catch
// - __cxa_rethrow

// Process termination
// Linux uses exit() from libc
extern "C" void exit(int status);

// RTTI support (not yet implemented for Linux)
// TODO: Implement Linux RTTI using Itanium C++ ABI
// This requires generating typeinfo structures and vtables

#endif
